# Generated by Django 5.0.4 on 2024-04-09 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players_stats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_id", models.CharField(max_length=100, unique=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=256, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Squad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True, default=None, max_length=256, null=True
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players_stats.players",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matches_data.teams",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matches",
            fields=[
                ("match_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("venue", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("current", "Current"),
                            ("finished", "Finished"),
                        ],
                        default="upcoming",
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "team_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_1_matches",
                        to="matches_data.teams",
                    ),
                ),
                (
                    "team_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_2_matches",
                        to="matches_data.teams",
                    ),
                ),
            ],
        ),
    ]
