# Generated by Django 5.0.4 on 2024-04-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Players",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=256)),
                ("matches_played", models.IntegerField()),
                ("runs", models.IntegerField()),
                ("average", models.FloatField(blank=True, default=None, null=True)),
                ("strike_rate", models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
